WIP: Add Card function and actions
telekom/voice-skill-sdk pull request #17
Opened 2020-12-08 11:54 UTC by tvadim

2020-12-08 12:19 UTC, Hingo approved these changes
Just scamming through it, looks good.

2020-12-16 10:15 UTC, 4thel00z requested changes

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +                        "aos={AosPackageName}&" \
use snake case for formatting placeholders

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +    use_kit: Kit
put this above class Kit since it looks a mistake (not indented attrib.)

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +        parameters = kwargs or None
why not {}?

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +        BLUETOOTH_PAIRING = "bluetooth_pairing"
not sure we want to expose this

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +        Set a timer
remove superfluous comment...

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +    Timer kit: set/cancel a timer
explain what a timer is maybe

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +    __slots__ = (
y not use dataclass?

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
>      def dict(self):
support interop with `vars` maybe

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +        card = card or Card(
assign directly to self.card, never overwrite initial parameter values

2020-12-16 10:15 UTC, 4thel00z commented on skill_sdk/responses.py
> +    __iter = (getattr(d, '__slots__', None)
I see now why you use `__slots__` there has to be a better way tho, for example supporting `vars`

2020-12-16 10:27 UTC, tvadim commented on skill_sdk/responses.py
> +        parameters = kwargs or None
If it's empty, it will be exported like 
``` 
{'use_kit': {'kit_name': 'audio_player', 'action': 'stop', 'parameters': {}}}
``` 

if `None`, the parameters will be completely out

2020-12-16 10:28 UTC, tvadim commented on skill_sdk/responses.py
> +    __slots__ = (
Good catch! I think I'd rather use `NamedTuple` - there are no dict-like changing operations on a card.

2020-12-16 10:30 UTC, tvadim commented on skill_sdk/responses.py
> +        BLUETOOTH_PAIRING = "bluetooth_pairing"
You mean, `BLUETOOTH_PAIRING`? What could be wrong with volumes?

2020-12-18 13:41 UTC, merged