Extending the add operator for messages to the key attribute
telekom/voice-skill-sdk pull request #54
Opened 2021-05-17 12:23 UTC by Anrufliste

Keeping concatenating consistent to key level.

2021-06-10 09:28 UTC, tvadim requested changes

2021-06-10 14:10 UTC, Anrufliste commented on skill_sdk/i18n.py
> +    def _adding_keys(self, key_first: str, key_second: str) -> str:
Adapted

2021-06-10 14:11 UTC, Anrufliste commented on skill_sdk/i18n.py
> +            key_first[-1] in MESSAGE_KEY_SEPARATORS
Hi it is not trying to avoid duplicates (so no removing), it should just guarantee, if no seperator is present, it will add a default one between the keys, to maintain readability. I will add a better comment.

2021-06-10 14:29 UTC, Anrufliste commented on skill_sdk/i18n.py
> +        return key_first + MESSAGE_KEY_DEFAULT_SEPARATOR + key_second
adding this to test case data and fix it with two len() checks

2021-06-10 15:14 UTC, Anrufliste commented on skill_sdk/i18n.py
>              value = self.value + other.value
The problem is, that the value ends with a separator like a "." by a high probability, while the keys not. So to avoid something like "KEYAKEYB" "Value A. Value B?"

And keys will be added with value if its just a string and not a message. During implementation I thought about adding a string in " into the key like :

KEYA " " KEYB

for a + " " + b with a and b being a Message.

Would you prefer this approach, so that it is a clearly different concatenation?

2021-06-26 11:28 UTC, Anrufliste commented
This has already been included in the [1.1.0 Release](https://github.com/telekom/voice-skill-sdk/releases/tag/1.1.0)

2021-06-26 11:28 UTC, closed without merging